# Generated by Django 5.2.5 on 2025-08-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Quốc gia'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Họ và Tên'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='japanese_level',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Trình độ tiếng Nhật'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại'),
        ),
    ]
