# Generated by Django 5.0.6 on 2025-08-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_enrollment_options_enrollment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Thời lượng video bài học (phút)', verbose_name='Video Duration (minutes)'),
        ),
    ]
