# Generated by Django 5.2.5 on 2025-08-27 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên giảng viên')),
                ('bio', models.TextField(blank=True, verbose_name='Giới thiệu')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='teachers/avatars/', verbose_name='Ảnh đại diện')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Chức danh')),
                ('experience', models.CharField(blank=True, max_length=255, verbose_name='Kinh nghiệm')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.teacher', verbose_name='Giảng viên'),
        ),
    ]
