# Generated by Django 5.2.5 on 2025-08-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_teacher_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.TextField(blank=True, verbose_name='Kinh nghiệm'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.TextField(blank=True, verbose_name='Chức danh'),
        ),
    ]
