# Generated by Django 5.2.5 on 2025-08-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_teacher_experience_alter_teacher_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True, verbose_name='Slug'),
        ),
    ]
