# Generated by Django 5.2.5 on 2025-08-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Bỏ chọn để ẩn khoá học này khỏi người dùng', verbose_name='Công khai'),
        ),
    ]
