# Generated by Django 5.2.5 on 2025-08-28 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Chọn phần cho bài học (ví dụ: Từ vựng, Ngữ pháp, Luyện đề, ...)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Bỏ chọn để ẩn khoá học này khỏi người dùng', verbose_name='Public'),
        ),
    ]
