# Generated by Django 5.0.6 on 2025-08-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_submission_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text="Giải thích chi tiết cho câu hỏi, hiển thị khi người dùng bấm 'xem giải thích chi tiết'.", null=True, verbose_name='Giải thích chi tiết'),
        ),
    ]
